import { Grid, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { DetailComponent } from '../components/DetailComponent'
import styles from '../styles/Home.module.css'



const Detail: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Detail</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>

                <Grid container columns={12} spacing={2}>
                    <Grid item xs={12}>
                        <Typography variant="h3" gutterBottom textAlign="center">
                            Detail
                        </Typography>
                    </Grid>
                    <Grid container columns={12} spacing={2}>
                        <Grid item xs={12} textAlign="center" padding="100%" marginTop="2%" className={styles.bod}><DetailComponent/></Grid>
                    </Grid>
                    <Grid container columns={12} spacing={2}>
                        <Grid item xs={12} textAlign="center" bottom="0" width="100%">
                            Footer
                        </Grid>
                    </Grid>
                </Grid>
            </div>
        </div>
    )
}

export default Detail