import { Grid, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Sidebar } from '../components/Sidebar'
import styles from '../styles/Home.module.css'
import { InputCrypto } from '../components/InputCrypto';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Crypto Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Grid container columns={12} spacing={2}>
          <Grid item xs={2.5} textAlign="center"></Grid>
          <Grid item xs={9.5}>
            <Typography variant="h3" gutterBottom textAlign="center">
              Crypto portfolium
            </Typography>
          </Grid>
          <Grid container columns={12} spacing={2}>
            <Grid container columns={12} spacing={2}>
              <Grid item xs={2.5} textAlign="center" marginTop="2%"><Sidebar /></Grid>
              <Grid item xs={9.5} textAlign="center" padding="100% 0%" marginTop="2%" className={styles.bod}><InputCrypto/></Grid>
            </Grid>
          </Grid>
          <Grid container columns={12} spacing={2}>
            <Grid item xs={12} textAlign="center" bottom="0" width="100%">
              Footer
            </Grid>
          </Grid>
        </Grid>
      </div>
    </div>
  )
}

export default Home
